### ISSUE TITLE
file starting with attribute raised as invalid

### ISSUE THREAD

**Issue by orpharion** [nexantic/intellij-cue#27]
input:

```
@if(this)
import "strconv"
_: strconv
a: 1
```
cue eval translation.cue --inject this

```
a: 1
```

plugin incorrectly identifies the following error:

```
@if(this)
import >"strconv"
_: strconv
a: 1
```

`>: ',', ':' or '=' expected, got '"'`

@if() is a file attribute that affects the build process - it is ignored if the attribute value isn't injected

**Comment by orpharion** [comment]
also occurs if the tag is changed from @if to @who, so it's not due to being a keyword

**Comment by jansorg** [comment]
Thanks, this will be fixed with the next update.
