### ISSUE TITLE
trailing bracket on ellipsis multi-line list not parsed correctly

### ISSUE THREAD

**Issue by orpharion** [nexantic/intellij-cue#35]
contents of `list-ellipsis-multi.cue`:
```
a: [
    ...
    string
]
```

```sh
$ cue def list-ellipsis-multi.cue
a: [...string]
```

Error reported by intellij-cue:
```
a: [
    ...
    string<1
]<2
```
1> ']' expected
2> <expression> expected, got ']'

**Comment by jansorg** [comment]
Fixed for the next update.
The language specification wasn't clear about this rule, so I had (insufficient) changes in this plugin's grammar.
I fixed it in the plugin and submitted https://github.com/cuelang/cue/issues/823.
