### ISSUE TITLE
shouldn't be implicit comma separator on newlines within lists

### ISSUE THREAD

**Issue by orpharion** [nexantic/intellij-cue#36]
content of list-ellipsis-multi-reverse.cue:
```
a: [
    {b: 1}
    ...
]

```

expected:
```
$ cue def list-ellipsis-multi-reverse.cue
missing ',' before newline in list literal:
    .\list-ellipsis-multi-reverse.cue:3:5
```

intellij-cue plugin doesn't pick up this error.

There is no implicit separator on newlines within lists: e.g. content of list-multi.cue:

```
a: [
    1
    2
] 

```

```
$ cue def .\list-multi.cue
missing ',' before newline in list literal:
    .\list-multi.cue:3:5
missing ',' in list literal:
    .\list-multi.cue:5:2
```

which intellij-cue also doesn't identify as an error.

This does feel unintuitive on cuelang's end, considering newline is an implicit separator in the context of structs.

**Comment by jansorg** [comment]
Now fixed for the update
